### PR TITLE
Fix an issue that allowed users to create private discussions with users who are blocking them

### LINKED ISSUE #173: "Block private discussions" in profile settings does not work
## Bug Report

**Current Behavior**
When a user enables the "Block private discussions" option in the profile settings, this option disappears in one place but still exists in another which still allows you to write private messages to that user.

**Steps to Reproduce**
1. Enable the "Block private discussions" option in your profile settings
2. Create a private discussion with this user from another account

**Expected Behavior**
As you can see in the video below, only one button disappears. The option to create private discussions should disappear completely. Additionally, this should be verified on the server side, because even if you hide the buttons, someone will be able to create a private discussion through the API.

**Screenshots**

https://user-images.githubusercontent.com/25438601/174478051-ff86057d-790f-4d8b-94a3-1d643f526de6.mp4

**Environment**
- Flarum version: 1.3.1
- Extension version: 1.1.6
- PHP version: 8.0

### PR DESCRIPTION
**Pull request by rafaucau**
**Fixes #173**

**Changes proposed in this pull request:**
This PR fixes an issue that allowed users to create private discussions with users who are blocking them.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes.

### CODE REVIEW

File: js/src/forum/helpers/canStartPrivateDiscussion.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import app from 'flarum/forum/app';
+
+export default (recipient) =>
+  app.session.user &&
+  app.session.user.id() !== recipient.id() &&
+  app.forum.attribute('canStartPrivateDiscussion') &&
+  (recipient.blocksPd() === false || (app.forum.attribute('canStartPrivateDiscussionWithBlockers') && recipient.cannotBeDirectMessaged()));
```
Comment (davwheat) [inline js/src/forum/helpers/canStartPrivateDiscussion.js:7]:
```suggestion
export default function canStartPrivateDiscussion(recipient) {
  return app.session.user &&
    app.session.user.id() !== recipient.id() &&
    app.forum.attribute('canStartPrivateDiscussion') &&
    (!recipient.blocksPd() || (app.forum.attribute('canStartPrivateDiscussionWithBlockers') && recipient.cannotBeDirectMessaged())); 
}
```

**Review by davwheat — COMMENTED** [review]
I _think_ this is fine.

I see some other things which I want to question in the code, but nothing that wasn't already there before this PR, so I'm happy to get this merged.

Nowadays for our JS, we tend to prefer named functions rather than arrow ones. This is because it makes it easier to debug when issues occur (since DevTools will show the function name rather than "anonymous", for example).

**Comment by rafaucau** [comment]
@davwheat Ok, I changed this function

**Review by davwheat — APPROVED** [review]
