### PR TITLE
Fixed `RecipientLabel` link being `true` instead of link to user profile

### LINKED ISSUE #157: Participant-links don't link to profile but /d/true
## Bug Report

**Current Behavior**
Links to the participants of a private discussion link to `/d/true` instead of `/u/username`.

**Steps to Reproduce**
1. Create a private discussion between users
2. Click on the link of either participant

**Expected Behavior**
Link to the user profile `/u/username`.

**Screenshots**
grafik

**Environment**
- Flarum version: 1.0.3
- Extension version: 1.0.0-beta.7
- Website URL: --
- Webserver: nginx
- Hosting environment: VM
- PHP version: 7.4.3
- Browser: Firefox 89.0.2

```
Flarum core 1.0.3
PHP version: 7.4.3
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imagick, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+---------------------------+--------------+--------+
| Flarum Extensions         |              |        |
+---------------------------+--------------+--------+
| ID                        | Version      | Commit |
+---------------------------+--------------+--------+
| flarum-flags              | v1.0.0       |        |
| flarum-suspend            | v1.0.0       |        |
| fof-formatting            | 1.0.0        |        |
| flarum-approval           | v1.0.0       |        |
| flarum-tags               | v1.0.3       |        |
| flarum-lang-german        | 1.1.0        |        |
| askvortsov-auto-moderator | v0.1.1       |        |
| fof-terms                 | 1.0.0        |        |
| fof-split                 | 1.0.0        |        |
| fof-socialprofile         | 1.0.0        |        |
| fof-links                 | 1.0.0        |        |
| flarum-nicknames          | v1.0.0       |        |
| flarum-bbcode             | v1.0.0       |        |
| flarum-lang-english       | v1.0.0       |        |
| flarum-likes              | v1.0.0       |        |
| flarum-lock               | v1.0.0       |        |
| flarum-markdown           | v1.0.1       |        |
| flarum-mentions           | v1.0.0       |        |
| flarum-statistics         | v1.0.0       |        |
| flarum-sticky             | v1.0.0       |        |
| flarum-subscriptions      | v1.0.0       |        |
| fof-upload                | 1.0.1        |        |
| fof-pages                 | 1.0.1        |        |
| fof-user-bio              | 1.0.0        |        |
| fof-merge-discussions     | 1.0.0        |        |
| fof-amazon-affiliation    | 1.0.0        |        |
| fof-byobu                 | 1.0.0-beta.7 |        |
+---------------------------+--------------+--------+

```

**Possible solution(s)**

**Additional Context**

### PR DESCRIPTION
**Pull request by iPurpl3x**
**Fixes #157**

**Changes proposed in this pull request:**

Actually create a link and don't just pass `true` as `href` attr.

**Reviewers should focus on:**
If the links work fine now

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

File: js/src/forum/pages/labels/RecipientLabel.tsx [hunk 1]
```diff
@@ -18,7 +18,10 @@ export default class RecipientLabel extends Component<IRecipientLabelAttrs> {
 
         newAttrs.style = newAttrs.style || {};
         newAttrs.className = classList('RecipientLabel', newAttrs?.className);
-        newAttrs.href = link;
+
+        if (link) {
+            newAttrs.href = app.route.user(recipient);
```
Comment (imorland) [inline js/src/forum/pages/labels/RecipientLabel.tsx:23]: Although this will certainly fix the `true` link if the route is to a `user`, but what about when the recipient is a `group` instead?

Comment (iPurpl3x) [reply js/src/forum/pages/labels/RecipientLabel.tsx:23]: My last commit should fix that now.

**Review by imorland — APPROVED** [review]
